### ISSUE TITLE
Mid Evaluation

### ISSUE THREAD

**Issue by khyatibhuva** [nisargptl/vehicle-recognition#14]
Upload Mid Evaluation Document for TA's and Professor's reference in Assignment repository. Create new directory Mid Evaluation and upload the file in pdf format.

**Comment by nisargptl** [comment]
[Mid Evaluation SE G23.pdf](https://github.com/nisargptl/vehicle-recognition/files/6265953/Mid.Evaluation.SE.G23.pdf)
Done

**Comment by khyatibhuva** [comment]
Noted.
