### ISSUE TITLE
Queries in Firebase

### ISSUE THREAD

**Issue by khyatibhuva** [nisargptl/vehicle-recognition#17]
Submit your necessary files that you have worked with in Firebase for trial,

**Comment by vishal-2504** [comment]
Firestore Database created in firebase. The file cars.json contains the car data in json format which is stored as a json tree in the firestore database using file uploader.js
For the trial purpose, I initialized the firestore app in index.html and queried the database in the file app.js

**Comment by khyatibhuva** [comment]
Attach the files for the same.

**Comment by vishal-2504** [comment]
Necessary files used are uploaded.

**Comment by khyatibhuva** [comment]
Can you upload your files here in this issue for reference?

**Comment by vishal-2504** [comment]
[Demo.zip](https://github.com/nisargptl/vehicle-recognition/files/6291564/Demo.zip)

**Comment by khyatibhuva** [comment]
Noted
