### ISSUE TITLE
Feedback on Website

### ISSUE THREAD

**Issue by khyatibhuva** [nisargptl/vehicle-recognition#18]
Everyone please review website and suggest some improvements.

**Comment by ajaykvala** [comment]
I guess there isn't much to improve but Front-end team can work upon the points mentioned in yesterday's meeting such as image centering, front-end for recommendations, etc. Also Front-end part being centered around design and making the UI more attractive, there will always be something better. So currently, focusing on the points discussed earlier should be enough for now and then we can have a quick review again.
Auto-complete feature in the compare section is really great !!

**Comment by khyatibhuva** [comment]
Thanks Ajay for your valuable feedback. We will start improvising on the feedback you gave us.
