### ISSUE TITLE
Entire Website

### ISSUE THREAD

**Issue by khyatibhuva** [nisargptl/vehicle-recognition#20]
Upload all necessary files today after we are done with changes suggested to us in feedback.

**Comment by shabbirmur** [comment]
Some of the files are yet to be updated from the backend part, should be done soon

**Comment by khyatibhuva** [comment]
Shabbir, you can continuing working on back end part. Your deadline is not today. This instruction was only for Front End people.

**Comment by 201801184** [comment]
[website.zip](https://github.com/nisargptl/vehicle-recognition/files/6291661/website.zip)

**Comment by khyatibhuva** [comment]
Noted
