### ISSUE TITLE
Current Updates

### ISSUE THREAD

**Issue by khyatibhuva** [nisargptl/vehicle-recognition#22]
1) Model Team: They are done with working Model. As there is still room for improvement, they are trying to improve accuracy.
2) Back End Team: Model & Backend and Database & Backend integration done. Integration of Front End and Backend is under progress. 
3) Front End Team: Website without integration is done. Touch ups are pending after integration will be done.
4) Database Team: They are done with ground work collection of data. They are assisting Back End Team to run queries. 

Any member of each team can update their progress here in this issue and seek help of other members. Keep Going everyone!!

**Comment by khyatibhuva** [comment]
One of the members of each team, kindly update on pending work.

**Comment by shabbirmur** [comment]
The codes for the queries will be done by this weekend.

**Comment by shabbirmur** [comment]
Integration of frontend to backend will be done by today

**Comment by 201801184** [comment]
we are doing minor touch ups while the integration is done

**Comment by nisargptl** [comment]
Few improvements to be incorporated 
1. Front-end Team - In Compare page provide two divisions below submit button. 
2. Model Team - Prediction Process has some issues. Output is not coming as expected when we tried some testing. Please look into it. [Urgent]

**Comment by khyatibhuva** [comment]
Palak and I will take care of first issue. Second issue will be taken care of by Swapnil.

**Comment by nisargptl** [comment]
Recommendation part still remains to be completed. Shabbir will you be able to complete it?

**Comment by VermaPalak106** [comment]
Khyati and I  have done the changes that were nedded

**Comment by shabbirmur** [comment]
Yeah, I'll finish it. I'll let you know if there's any problem.

**Comment by nisargptl** [comment]
Compare Page is done, now filter page is remaining which I'll be completing in 3-4 days.

**Comment by shabbirmur** [comment]
Recommendation functionality has been added. Images of the recommended are yet to added.

**Comment by shabbirmur** [comment]
Database Team: Mohil and Vishal, please get the images ready

**Comment by nisargptl** [comment]
Good job @shabbirmur, upload those files here, I'll merge them with the project.

**Comment by vishal-2504** [comment]
Regarding the image database, we are working on it.

**Comment by khyatibhuva** [comment]
Whoever was assigned image database task (in new issue), let's try to complete before exams.

**Comment by Mohil027** [comment]
Regarding the image database, the images have been uploaded. Currently, starting the work for the unfinished documentation part.

**Comment by nisargptl** [comment]
Filter page is done. So, now all the functionalities have been added and all the pages have been routed. Now, only the image database integration part is remaining.

**Comment by shabbirmur** [comment]
Contact us page has been routed. Great work frontend team

**Comment by khyatibhuva** [comment]
Thanks Shabbir. Then we did two meeting between front end and integration team to complete the touch ups of the website. It mostly included styling of website.

**Comment by sjdhola** [comment]
Before this meeting was conducted model team had completed model testing, black box testing as well as static analysis.

**Comment by Mohil027** [comment]
Prior to this meeting, the database team formatted the final csv version of the dataset. Our team also completed the testing on the Postgre SQL . Also, the image database for filter page that consisted of image of cars for all the cars in our dataset was also formed with the help of the teammates. The dataset was formatted in a way such that the pixel dimensions for all the images were (800 x 305) as required by the frontend team

**Comment by ajaykvala** [comment]
While unit testing was under progress, integration team went on to test the integration work. We had ensured that each and every variable and the requests that were exchanged between pages were correct and were carrying correct values. We had to make sure there were no libraries that were being imported without use. We also ensured that there were no loopholes left once the complete integration was done.

**Comment by VermaPalak106** [comment]
In GUI Testing we tested all the functionalities for its valid and invalid. We checked if the alerts are shown where they are supposed to be. We also checked sticky feature on filter page. We checked usability. We checked if all the components in GUI are functional. We also tested if the colors chosen are suitable and do not create a harsh impression on the user. All the Screenshots are added to the final document.

**Comment by ajaykvala** [comment]
After the unit testing of each team was completed, integration testing was started.

**Comment by khyatibhuva** [comment]
Then we conducted a meeting to perform system testing.

**Comment by khyatibhuva** [comment]
Next we planned to complete our documentation, presentation and video etc. We divided our work equally and completed it.

**Comment by khyatibhuva** [comment]
In one last meeting, we had a thorough introspection of where we started, how we performed and had a open conversation with each other. Then finally we had a run through of our product presentation.

**Comment by ajaykvala** [comment]
This project helped me to explore previously uncharted domains. I am really glad that I am a part of this project and I am more than happy with the performance and cohesiveness of our group. Thank you, all.

**Comment by sjdhola** [comment]
Lerant a lot and enjoyed the work so much. Thank you, all.

**Comment by VermaPalak106** [comment]
I project helped me to explore further in designing of website. I am happy to be part of the group .Thank you

**Comment by shabbirmur** [comment]
My experience doing this project was great. Got to learn so many new things and really enjoyed working with you, Thanks everyone.

**Comment by vishal-2504** [comment]
Throughout the process of development of product, I got an opportunity to explore many technical domains and learned much about the same. I enjoyed being a part of this team. Thank you

**Comment by Mohil027** [comment]
Along with learning some technical skills, this project helped me improving other skills like team work, completion of milestones in required time period, etc. I'm really glad that I am part of this project and really enjoyed working with this team. Thank you.

**Comment by 201801184** [comment]
This project was a great experience for my future. I came to know new things through this project. It was a great pleasure to be a part of this group. gracias!

**Comment by 201801196** [comment]
It was a great experience. I learned a lot. Thank you

**Comment by khyatibhuva** [comment]
We actually implemented theory into practical and learned a lot by solving challenges. It was great to work with all the team members to create such a nice project.

**Comment by nisargptl** [comment]
It was a great project and a good team to work with. Gained a lot of experience working on the project and it was overall an awesome experience.
