### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by khyatibhuva** [nisargptl/vehicle-recognition#23]
Instead of two divisions, create 8 divisions (4 pairs of divisions of image and text separately). One pair should be in first parallax upload and the other three in recommendation.

**Comment by 201801184** [comment]
[website.zip](https://github.com/nisargptl/vehicle-recognition/files/6311360/website.zip)

**Comment by 201801184** [comment]
we are doing minor touch-ups while the integration is done
