### ISSUE TITLE
Image Database

### ISSUE THREAD

**Issue by nisargptl** [nisargptl/vehicle-recognition#24]
We need to create new Images Dataset so that we will be able to display those images of cars during recommendation and filter page. The pixel dimensions need to be 800x305 px.

**Comment by khyatibhuva** [comment]
Noted. Let's work according to what we discussed in meeting.

**Comment by khyatibhuva** [comment]
Let's complete this issue before exams start.

**Comment by 201801184** [comment]
[Cars_resized(54-71).zip](https://github.com/nisargptl/vehicle-recognition/files/6372815/Cars_resized.54-71.zip)
I have resized the car images (54 to 71)
according to the final_car_details_2

**Comment by 201801184** [comment]
[54-71.zip](https://github.com/nisargptl/vehicle-recognition/files/6409016/54-71.zip)
I have uploaded the resized images from 54-71 having the dimensions 800x305px

**Comment by 201801196** [comment]
[72-89.zip](https://github.com/nisargptl/vehicle-recognition/files/6409025/72-89.zip)

**Comment by 201801196** [comment]
[72_89.zip](https://github.com/nisargptl/vehicle-recognition/files/6409044/72_89.zip)

**Comment by VermaPalak106** [comment]
[18_35.zip](https://github.com/nisargptl/vehicle-recognition/files/6409505/18_35.zip)
dimensions are 800px x 305px for most of the photos.There are only two three of them with 310px

**Comment by VermaPalak106** [comment]
the images of Bentley Mulsanne and BMW Z4 Convertible are in webp format instead of jpg. will it work or should I change their format??

**Comment by nisargptl** [comment]
No problem, I have changed it.

**Comment by Mohil027** [comment]
The images for the cars with serial no. 1-17 have been found and resized according to the required specifications (800 x 305  pixels)
[1_17.zip](https://github.com/nisargptl/vehicle-recognition/files/6410904/1_17.zip)

**Comment by Mohil027** [comment]
The images for the cars with serial no. 1-17 from the databases have been found, resized according to the specifications (800 x 305 pixels) and uploaded here.
[Uploading 1_17.zip…]()

**Comment by Mohil027** [comment]
The images for the cars with serial no. 1-17 from the databases have been found, resized according to the specifications (800 x 305 pixels) and uploaded here.
[1_17.zip](https://github.com/nisargptl/vehicle-recognition/files/6410907/1_17.zip)

**Comment by vishal-2504** [comment]
The images of the cars from 36 to 53 are collected and resized according to the requirements.
[36_53.zip](https://github.com/nisargptl/vehicle-recognition/files/6410931/36_53.zip)

**Comment by khyatibhuva** [comment]
I have uploaded images from index 90 to 101 in excel.

[cars.zip](https://github.com/nisargptl/vehicle-recognition/files/6411845/cars.zip)

**Comment by khyatibhuva** [comment]
I crossed. Everyone has uploaded.
