### ISSUE TITLE
Ordering issue in CSV file and image dataset.

### ISSUE THREAD

**Issue by sjdhola** [nisargptl/vehicle-recognition#25]
There is ordering issue in car names in CSV file (For car names) and image dataset. So, due to which image prediction is not working properly. In CSV file (For car names), names are ordered by case sensitive and in image dataset names are not ordered by case sensitive. So, we have to make them same and do necessary changes in CSV file (For car names) to make them in same order.

**Comment by 201801196** [comment]
[Car_names.csv](https://github.com/nisargptl/vehicle-recognition/files/6348418/Car_names.csv)

updated CSV file

**Comment by khyatibhuva** [comment]
Noted.
