### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by nisargptl** [nisargptl/vehicle-recognition#26]
The Car Names list and Car Details database are not in sync. 
[Car_names.csv](https://github.com/nisargptl/vehicle-recognition/files/6348424/Car_names.csv)
[final_car_details_2.csv](https://github.com/nisargptl/vehicle-recognition/files/6348436/final_car_details_2.csv)
Changes are to be made in final_car_details_2 file as per the names in Car_names file.

**Comment by khyatibhuva** [comment]
Noted. Working on it. Will send you today itself.

**Comment by khyatibhuva** [comment]
Done. 

[final_car_details_2_corrected.xlsx](https://github.com/nisargptl/vehicle-recognition/files/6358098/final_car_details_2_corrected.xlsx)

For comparing values, we used pandas library. Swapnil, can you please upload the code also?

**Comment by sjdhola** [comment]
`import pandas as pd
import numpy as np
data1 = pd.read_csv("/content/Car_names.csv",header=None)
data2 = pd.read_csv("/content/final_car_details_2.csv")
x=np.array(data2['Name'])
y=np.array(data1[0])
x=sorted(x)
y=sorted(y)
cnt=0
for i in range(100):
  if x[i]!=y[i]:
    print(i,x[i],"!=",y[i])
    cnt+=1`

**Comment by khyatibhuva** [comment]
Thank you.
