### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by khyatibhuva** [nisargptl/vehicle-recognition#3]
Database queries are pending to be posted.

**Comment by khyatibhuva** [comment]
Shabbir will be joining you to help write queries.

**Comment by khyatibhuva** [comment]
Any updates?

**Comment by nisargptl** [comment]
Database queries for Home page and compare page have been completed. Now, only filter page is remaining.

**Comment by khyatibhuva** [comment]
If possible, attach queries of the pages who are done with.

**Comment by nisargptl** [comment]
filter page queries have also been completed. Closing this issue.
