### ISSUE TITLE
 Discrepancy in testing image dataset

### ISSUE THREAD

**Issue by sjdhola** [nisargptl/vehicle-recognition#42]
While testing the model we are getting very less accuracy for predicting car class "Chevrolet Silverado 1500 Classic Extended Cab 2007". In image dataset there is no class "Chevrolet Silverado 1500 Classic Extended Cab 2007" available in testing dataset but instead there is class present named "Chevrolet Silverado 1500 Classic Extended Cab 2012". Both are the different class. So, model is giving less accuracy for given class. So, change in image dataset is required to solve this issue.

**Comment by 201801196** [comment]
we have changed the car dataset to Chevrolet Silverado 1500 Classic Extended Cab 2007 in testing dataset now we are getting 100% validation accuracy for the given class And we are getting 96% validation accuracy on entire 100 classes dataset.

**Comment by sjdhola** [comment]
Noted thank you for the help
